AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RetroPieBackup

  Sample SAM Template for RetroPieBackup

Parameters:
  SrcBucket:
    Type: String
    Description: Name of Bucket used for backups

Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cleanup/
      Handler: trigger.lambda_handler
      Runtime: python3.7
      Events:
        Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
